### ISSUE TITLE
Block页面显示触发的事件

### ISSUE THREAD

**Issue by chenzhitong** [RookieCoderrr/Neo-Explorer-UI#12]
比如这个页面，里面写 Transfers 1，但又看不到详情，我猜是燃烧手续费的Transfer事件，建议显示出来

http://106.14.204.151:8080/blockinfo/0xd98a583b8209d3be354892dd80253df81cb7727aec2afc91e691b8303229bfa2

**Comment by WSbaikaishui** [comment]
get 正在添加

**Comment by RookieCoderrr** [comment]
Function finished.
